/**
 * Cache for AI issue explanations.
 *
 * This is what makes the panel affordable. An audit snapshot is sealed and
 * immutable, and the rule text is pinned by `ruleVersion`, so the explanation
 * for a (audit, rule) pair never legitimately changes — without a cache the
 * feature would bill a model call every time somebody reopened a drawer.
 *
 * The key includes `organizationId` so an entry can never be served across
 * tenants, and `promptVersion` so changing the prompt invalidates everything
 * generated by the old one rather than silently mixing the two.
 */
import { buildCacheKey, getCached, setCached } from "@/server/lib/r2-cache";
import {
  explanationSchema,
  EXPLANATION_PROMPT_VERSION,
  type IssueExplanation,
} from "@/server/features/audit/issues/ai-explanation";

/**
 * Long TTL on purpose: every input to the key is immutable, so a stale entry
 * is not a correctness risk — only a wasted, re-billed regeneration is. Once
 * this expires, reopening an old issue silently charges the customer again for
 * an answer they already paid for, so the horizon is set well past the window
 * in which anyone realistically revisits an audit.
 *
 * Note for whoever adds audit retention: professional audits currently have no
 * sweep (the scheduled job only clears free-checker artifacts), and R2's TTL
 * here is soft — expiry is checked on read, nothing is physically deleted. So
 * these objects, which are derived from a customer's crawled pages, outlive
 * both this TTL and any future audit deletion unless the sweep removes them
 * explicitly.
 */
const EXPLANATION_TTL_SECONDS = 180 * 24 * 60 * 60;

interface ExplanationCacheKeyInput {
  organizationId: string;
  auditId: string;
  ruleId: string;
  ruleVersion: string;
  locale: string;
}

async function keyFor(input: ExplanationCacheKeyInput): Promise<string> {
  return buildCacheKey("audit:issue-explanation", {
    ...input,
    promptVersion: EXPLANATION_PROMPT_VERSION,
  });
}

/**
 * A cached explanation, or null. Re-validated against the schema on read: the
 * cache outlives deploys, so an entry written by an older shape must degrade
 * to a miss instead of reaching the UI as something it no longer matches.
 */
export async function getCachedExplanation(
  input: ExplanationCacheKeyInput,
): Promise<IssueExplanation | null> {
  const cached = await getCached(await keyFor(input));
  if (cached === null) return null;

  const parsed = explanationSchema.safeParse(cached);
  return parsed.success ? parsed.data : null;
}

export async function putCachedExplanation(
  input: ExplanationCacheKeyInput,
  explanation: IssueExplanation,
): Promise<void> {
  await setCached(await keyFor(input), explanation, EXPLANATION_TTL_SECONDS);
}
